defmodule Envoy.Type.Matcher.V3.HttpResponseStatusCodeMatchInput do
  @moduledoc """
  Match input indicates that matching should be done on the response status
  code.
  [#protodoc-title: Common HTTP Inputs]
  """

  use Protobuf,
    full_name: "envoy.type.matcher.v3.HttpResponseStatusCodeMatchInput",
    protoc_gen_elixir_version: "0.17.0",
    syntax: :proto3
end

defmodule Envoy.Type.Matcher.V3.HttpResponseStatusCodeClassMatchInput do
  @moduledoc """
  Match input indicates that the matching should be done on the class of the
  response status code. For eg: 1xx, 2xx, 3xx, 4xx or 5xx.
  """

  use Protobuf,
    full_name: "envoy.type.matcher.v3.HttpResponseStatusCodeClassMatchInput",
    protoc_gen_elixir_version: "0.17.0",
    syntax: :proto3
end

defmodule Envoy.Type.Matcher.V3.HttpResponseLocalReplyMatchInput do
  @moduledoc """
  This match input determines whether the response is a local reply which gets
  generated by Envoy or a response from the upstream.

  The input string is ``true`` for local replies and ``false`` for the upstream
  responses.

  It can be used with the ``custom_response`` filter to apply policies only to
  the Envoy generated local replies.
  [#extension: envoy.matching.inputs.local_reply]
  """

  use Protobuf,
    full_name: "envoy.type.matcher.v3.HttpResponseLocalReplyMatchInput",
    protoc_gen_elixir_version: "0.17.0",
    syntax: :proto3
end
